# Generated by Django 5.0.7 on 2024-08-13 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recipe',
            name='image',
        ),
        migrations.AddField(
            model_name='recipe',
            name='cover_image',
            field=models.ImageField(null=True, upload_to='recipes/cover_image/%Y/%m/%d'),
        ),
    ]
